# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e76877f7dde1a77a865214b1d52bb0e707dc29b0423253ea86bbdb8a715a53b093ae1b9b8741e1b095930c820a1b7b52f7ddf01eabecfbb54c1aa07b0949d6f3

test:
  secret_key_base: dc331a0bb1eb00d6d0b918dfe7de8e07353901eb00517847388a48b8673a6d3f97a5379d403a264e3edb25e2e0b23827e82d57e2ebf6173359a0ab0c9c58cc68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
